services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: avalia-tcc-app
    container_name: avalia-tcc-app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      APP_URL: http://localhost:8000
    volumes:
      - .:/var/www/html
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage

#  db:
#    image: postgres:15-alpine
#    container_name: amostra-pi-db
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: ${DB_DATABASE}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

